### ISSUE TITLE
About Disparity Estimation

### ISSUE THREAD

**Issue by MeLonJ10** [DandilionLau/Visually-Imbalanced-Stereo#1]
Hi Yicun,
Thanks for your wonderful job!
There is some confusion about the code. I could not find codes related to disparity prediction (e.g., stereo matching model, disparity map loading). Is there any misunderstanding?

**Comment by DandilionLau** [comment]
Hi MeLonJ10, thanks for the question! For this implementation, we used CRL (implementation can be found at https://github.com/Artifineuro/crl), which is a variant of DispNet to conduct the final stereo matching after views are restored. Ideally, the stereo matching model pre-trained on the standard KITTI dataset should have decent performance.
